### ISSUE TITLE
기존 번역

### ISSUE THREAD

**Issue by jaykwonpark** [rust-lang-ko/rust-by-example-ko#5]
기존 번역 (https://hanbum.gitbooks.io/rustbyexample/content/) 은 아직 완료하지 않은신 상태인 것 같은데, github repo 나 번역하신 분 연락처를 찾을 수가 없네요.

**Comment by jinto** [comment]
한국 러스트 사용자 모임 디스코드에 작업 상황을 공유했는데 https://discord.com/channels/487203989830631435/807864772342972477  이런 의견을 주셔서, 연락을 했고, 참여해주시기로 했습니다. 감사합니다.
